
### Create new User
POST localhost:3005/authentication/register
Content-Type: application/json

{
  "name": "Mbouna 2",
  "email": "msus2@gmail.com",
  "password": "1234567",
  "address": {
    "street": "Name of the Street",
    "city": "Name of the city",
    "country": "Name of the country"
  }
}

### Login user with email and password
POST localhost:3005/authentication/log-in
Content-Type: application/json

{
  "email": "msus2@gmail.com",
  "password": "1234567"
}

### Get User by ID
GET localhost:3000/users/2


### Get Authenticate User
GET localhost:3005/authentication

### Logout User
POST localhost:3000/authentication/log-out
