### Get All Posts
GET localhost:3000/posts

### Create a new Post
POST localhost:3000/posts
Content-Type: application/json

{
  "title": "Post 1",
  "content": "Content of Post 1"
}

### Delete post by id

DELETE localhost:3000/posts/2
